- left reads: [../../../data/input/B.faecium/std_right.cor.fastq.gz]
  orientation: fr
  right reads: [../../../data/input/B.faecium/std_left.cor.fastq.gz]
  single reads: [../../../data/input/B.faecium/std_left.cor_single.fastq.gz, ../../../data/input/B.faecium/std_right.cor_single.fastq.gz]
  type: paired-end
- left reads: [../../../data/input/B.faecium/CLIP_7.5kb_left.cor.fastq.gz]
  orientation: rf
  right reads: [../../../data/input/B.faecium/CLIP_7.5kb_right.cor.fastq.gz]
  single reads: [../../../data/input/B.faecium/CLIP_7.5kb_right.cor_single.fastq.gz,
    ../../../data/input/B.faecium/CLIP_7.5kb_left.cor_single.fastq.gz]
  type: mate-pairs
