- left reads: [../../../data/input/C.S.muelleri/bh20111221/09.reads.corrected.fastq.gz]
  orientation: fr
  right reads: [../../../data/input/C.S.muelleri/bh20111221/09.reads.corrected.fastq.gz]
  type: paired-end
