- left reads: [../../../data/input/E.coli/jcvi/big_jump/00.reads.right.reg.corrected.fastq]
  orientation: fr
  right reads: [../../../data/input/E.coli/jcvi/big_jump/00.reads.left.reg.corrected.fastq]
  single reads: [../../../data/input/E.coli/jcvi/big_jump/00.reads.left.reg.unpaired.fastq,
    ../../../data/input/E.coli/jcvi/big_jump/00.reads.right.reg.unpaired.fastq]
  type: paired-end
- left reads: [../../../data/input/E.coli/jcvi/big_jump/00.reads.left.jump.corrected.fastq]
  orientation: rf
  right reads: [../../../data/input/E.coli/jcvi/big_jump/00.reads.right.jump.corrected.fastq]
  type: mate-pairs
