- left reads: [../../../data/input/Bacteria/E.coli/K12/is220/MG1655-K12_IDEAL_2.fastq.gz]
  orientation: fr
  right reads: [../../../data/input/Bacteria/E.coli/K12/is220/MG1655-K12_IDEAL_1.fastq.gz]
  type: paired-end
