- left reads: [../../../data/input/Bacteria/E.coli/K12/is220_bh/04.reads.0.right.corrected.fastq.gz]
  orientation: fr
  right reads: [../../../data/input/Bacteria/E.coli/K12/is220_bh/04.reads.0.left.corrected.fastq.gz]
  single reads: [../../../data/input/Bacteria/E.coli/K12/is220_bh/04.reads.0.left.unpaired.fastq.gz,
    ../../../data/input/Bacteria/E.coli/K12/is220_bh/04.reads.0.right.unpaired.fastq.gz]
  type: paired-end
