[
  {
    orientation: "fr",
    type: "paired-end",
    right reads: [
      "/home/lab42/algorithmic-biology/assembler/data/input/E.coli/is220/cropped/s_6.first400000_2.fastq.gz"
    ],
    left reads: [
      "/home/lab42/algorithmic-biology/assembler/data/input/E.coli/is220/cropped/s_6.first400000_1.fastq.gz"
    ],
    single reads: [
    ]
  }
]

