- left reads: [../../../data/input/E.coli/jcvi/bh20111219/00.reads.right.corrected.fastq.gz]
  orientation: fr
  right reads: [../../../data/input/E.coli/jcvi/bh20111219/00.reads.left.corrected.fastq.gz]
  single reads: [../../../data/input/E.coli/jcvi/bh20111219/00.reads.left.unpaired.fastq.gz,
    ../../../data/input/E.coli/jcvi/bh20111219/00.reads.right.unpaired.fastq.gz]
  type: paired-end
- left reads: [../../../data/input/E.coli/jcvi/bh20111219/00.shearjump.left.corrected.fastq.gz]
  orientation: rf
  right reads: [../../../data/input/E.coli/jcvi/bh20111219/00.shearjump.right.corrected.fastq.gz]
  type: mate-pairs
