- left reads: [../../../data/input/HMP/lane_2_jumping/bh20111202/00.reads.right.short.corrected.fastq.gz]
  orientation: fr
  right reads: [../../../data/input/HMP/lane_2_jumping/bh20111202/00.reads.left.short.corrected.fastq.gz]
  single reads: [../../../data/input/HMP/lane_2_jumping/bh20111202/00.reads.left.short.unpaired.fastq.gz,
    '../../../data/input/HMP/lane_2_jumping/bh20111202/00.reads.right.short,unpaired.fastq.gz']
  type: paired-end
- left reads: [../../../data/input/HMP/lane_2_jumping/bh20111202/00.reads.left.long.corrected.fastq.gz]
  orientation: rf
  right reads: [../../../data/input/HMP/lane_2_jumping/bh20111202/00.reads.right.long.corrected.fastq.gz]
  type: mate-pairs
