- left reads: [../../../data/input/HMP/lane_8/bh20120701/00.reads.0.right.corrected.fastq]
  orientation: fr
  right reads: [../../../data/input/HMP/lane_8/bh20120701/00.reads.0.left.corrected.fastq]
  single reads: [../../../data/input/HMP/lane_8/bh20120701/00.reads.0.left.unpaired.fastq,
    ../../../data/input/HMP/lane_8/bh20120701/00.reads.0.right.unpaired.fastq]
  type: paired-end
