- left reads: [../../../data/input/P.stipitis/HCT10499_s_7_2.cor.fastq.gz]
  orientation: fr
  right reads: [../../../data/input/P.stipitis/HCT10499_s_7_1.cor.fastq.gz]
  single reads: [../../../data/input/P.stipitis/HCT10499_s_7_1.cor_single.fastq.gz,
    ../../../data/input/P.stipitis/HCT10499_s_7_2.cor_single.fastq.gz]
  type: paired-end
- left reads: [../../../data/input/P.stipitis/HCT10508_s_8_1.cor.fastq.gz]
  orientation: rf
  right reads: [../../../data/input/P.stipitis/HCT10508_s_8_2.cor.fastq.gz]
  single reads: [../../../data/input/P.stipitis/HCT10508_s_8_2.cor_single.fastq.gz,
    ../../../data/input/P.stipitis/HCT10508_s_8_1.cor_single.fastq.gz]
  type: mate-pairs
