- left reads: [../../../data/input/S.aureus/frag_2.cor.fastq.gz]
  orientation: fr
  right reads: [../../../data/input/S.aureus/frag_1.cor.fastq.gz]
  single reads: [../../../data/input/S.aureus/frag_1.cor_single.fastq.gz, ../../../data/input/S.aureus/frag_2.cor_single.fastq.gz]
  type: paired-end
- left reads: [../../../data/input/S.aureus/shortjump_1.cor.fastq.gz]
  orientation: rf
  right reads: [../../../data/input/S.aureus/shortjump_2.cor.fastq.gz]
  single reads: [../../../data/input/S.aureus/shortjump_2.cor_single.fastq.gz, ../../../data/input/S.aureus/shortjump_1.cor_single.fastq.gz]
  type: mate-pairs
