- left reads: [../../../data/input/S.smaragdinae/std_right.cor.fastq.gz]
  orientation: fr
  right reads: [../../../data/input/S.smaragdinae/std_left.cor.fastq.gz]
  single reads: [../../../data/input/S.smaragdinae/std_left.cor_single.fastq.gz, ../../../data/input/S.smaragdinae/std_right.cor_single.fastq.gz]
  type: paired-end
- left reads: [../../../data/input/S.smaragdinae/CLIP_6kb_left.cor.fastq.gz]
  orientation: rf
  right reads: [../../../data/input/S.smaragdinae/CLIP_6kb_right.cor.fastq.gz]
  single reads: [../../../data/input/S.smaragdinae/CLIP_6kb_right.cor_single.fastq.gz,
    ../../../data/input/S.smaragdinae/CLIP_6kb_left.cor_single.fastq.gz]
  type: mate-pairs
