 [
 {
   left reads: [/Johnny/data/projects/JCVI.SingleCell.PacBio/Tm6/Illumina/TM6MDA1_s_8_1_sequence.00.cor.fastq.gz],
   orientation: "fr",
   right reads: [/Johnny/data/projects/JCVI.SingleCell.PacBio/Tm6/Illumina/TM6MDA1_s_8_2_sequence.00.cor.fastq.gz],
   single reads: [/Johnny/data/projects/JCVI.SingleCell.PacBio/Tm6/Illumina/TM6MDA1_s_8__unpaired.00.cor.fastq.gz],
   type: "paired-end"
 },
 {
   orientation: "fr",
   type: "pacbio",
   single reads: [
     "/johnny/data/projects/JCVI.SingleCell.PacBio/Tm6/Tm6-1/Tm61-rawReads-Amp40x-1Cell.fastq"
   ]
 }
]

