- left reads: [../../../data/input/Bacteria/E.coli/K12/emul/MG1655-K12_emul2.fastq.gz]
  orientation: fr
  right reads: [../../../data/input/Bacteria/E.coli/K12/emul/MG1655-K12_emul1.fastq.gz]
  type: paired-end
