- left reads: [../../../data/input/Bacteria/E.coli/K12/is480/cropped/E.Coli_600.first10000_2.fastq.gz]
  orientation: fr
  right reads: [../../../data/input/Bacteria/E.coli/K12/is480/cropped/E.Coli_600.first10000_1.fastq.gz]
  type: paired-end
