- left reads: [../../../data/input/Bacteria/E.coli/K12/is220/cropped/s_6.first400000_2.fastq.gz]
  orientation: fr
  right reads: [../../../data/input/Bacteria/E.coli/K12/is220/cropped/s_6.first400000_1.fastq.gz]
  type: paired-end
