- left reads: [../../../data/input/Bacteria/E.coli/K12/is480/cropped/s_6.first1000000_2.fastq.gz]
  orientation: fr
  right reads: [../../../data/input/Bacteria/E.coli/K12/is480/cropped/s_6.first1000000_1.fastq.gz]
  type: paired-end
