- left reads: [../../../data/input/_deprecated_JCVI/JCVI_control_MDA_Ecoli_0512/hammer/00.reads.right.corrected.fastq.gz]
  orientation: fr
  right reads: [../../../data/input/_deprecated_JCVI/JCVI_control_MDA_Ecoli_0512/hammer/00.reads.left.corrected.fastq.gz]
  single reads: [../../../data/input/_deprecated_JCVI/JCVI_control_MDA_Ecoli_0512/hammer/00.reads.left.unpaired.fastq.gz,
    ../../../data/input/_deprecated_JCVI/JCVI_control_MDA_Ecoli_0512/hammer/00.reads.right.unpaired.fastq.gz]
  type: paired-end
- left reads: [../../../data/input/_deprecated_JCVI/JCVI_control_MDA_Ecoli_0512/hammer/00.shearjump.left.corrected.fastq.gz]
  orientation: rf
  right reads: [../../../data/input/_deprecated_JCVI/JCVI_control_MDA_Ecoli_0512/hammer/00.shearjump.right.corrected.fastq.gz]
  type: mate-pairs
