- left reads: [../../../data/input/_deprecated_JCVI/JCVI_control_MDA_Ecoli_0512/hammer_cropped/reads400000_right.fastq]
  orientation: fr
  right reads: [../../../data/input/_deprecated_JCVI/JCVI_control_MDA_Ecoli_0512/hammer_cropped/reads400000_left.fastq]
  single reads: [../../../data/input/_deprecated_JCVI/JCVI_control_MDA_Ecoli_0512/hammer_cropped/reads400000_single_left.fastq,
    ../../../data/input/_deprecated_JCVI/JCVI_control_MDA_Ecoli_0512/hammer_cropped/reads400000_single_right.fastq]
  type: paired-end
- left reads: [../../../data/input/_deprecated_JCVI/JCVI_control_MDA_Ecoli_0512/hammer_cropped/shearjump400000_left.fastq]
  orientation: rf
  right reads: [../../../data/input/_deprecated_JCVI/JCVI_control_MDA_Ecoli_0512/hammer_cropped/shearjump400000_right.fastq]
  type: mate-pairs
