- left reads: [../../../data/input/E.coli/SC_cor/hammer_human_filtered/filtered_paired_2_filtered.fastq]
  orientation: fr
  right reads: [../../../data/input/E.coli/SC_cor/hammer_human_filtered/filtered_paired_1_filtered.fastq]
  single reads: [../../../data/input/E.coli/SC_cor/hammer_human_filtered/filtered_single_1.fastq,
    ../../../data/input/E.coli/SC_cor/hammer_human_filtered/filtered_single_2.fastq]
  type: paired-end
